apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: devops
    - name: trainer
      value: "siva"



# env in docker is if you change env we should rebuild tje docker image 
# env in k8 just restart is enough